module.exports = {
  associate: models => {
    models.departments.hasMany(models.users, {foreignKey: "departmentId"})
    models.roles.hasMany(models.users, {foreignKey: "roleId"})
    models.statuses.hasMany(models.users, {foreignKey: "statusId"})

    models.approverList.belongsTo(users, {foreignkey: "user_getsapproved"});
    models.approverList.belongsTo(users, {foreignkey: "user_approver"});
    models.assetList.belongsTo(assetStatus, {foreignkey: "assetStatusId"});
    models.assetList.belongsTo(assetType, {foreignkey: "assetTypeId"});
    models.assetList.belongsTo(vendors, {foreignkey: "vendorId"});
    models.assetList.belongsTo(users, {foreignkey: "userId"});
    models.auditLog_access.belongsTo(users, {foreignkey: "auditLog_access_userId"});
    models.auditLog_approvals.belongsTo(users, {foreignkey: "auditLog_approvals_userId"});
    models.auditLog_changeRequests.belongsTo(users, {foreignkey: "auditLog_changeRequests_userId"});
    models. auditLog_changeRequests.belongsTo(changeRequests, {foreignkey: "auditLog_changeRequests_requestId"});
    models.auditLog_incidents.belongsTo(users, {foreignkey: "auditLog_incidents_userId"});
    models.auditLog_incidents.belongsTo(incidentLog, {foreignkey: "auditLog_incidents_incidentId"});
    models. auditLog_tasks.belongsTo(users, {foreignkey: "auditLog_tasks_userId"});
    models.auditLog_tasks.belongsTo(taskList, {foreignkey: "auditLog_tasks_taskId"});
    models.auditLog_tickets.belongsTo(users, {foreignkey: "auditLog_tickets_userId"});
    models.auditLog_tickets.belongsTo(ticketLog, {foreignkey: "auditLog_tickets_ticketId"});
    models.changeRequests.belongsTo(changeRequestType, {foreignkey: "changeRequestTypeId"});
    models.changeRequests.belongsTo(users, {foreignkey: "changeRequest_owner"});
    models.changeRequests.belongsTo(users, {foreignkey: "changeRequest_approver"});
    models.changeRequests.belongsTo(changeRequestStatus, {foreignkey: "changeRequestStatusId"});
    models.contracts.belongsTo(vendors, {foreignkey: "vendorId"});
    models.faqList.belongsTo(faqCategory, {foreignkey: "faq_categoryId"});
    models.incidentLog.belongsTo(users, {foreignkey: "incident_assignedUser"});
    models.incidentLog.belongsTo(users, {foreignkey: "incident_createdBy"});
    models.incidentLog.belongsTo(incidentStatus, {foreignkey: "incidentStatusId"});
    models.incidentLog.belongsTo(incidentType, {foreignkey: "incident_typeId"});
    models.incidentLog.belongsTo(incidentUrgency, {foreignkey: "incidentUrgencyId"});
    incidentLog.belongsTo(locations, {foreignkey: "incident_location"});
    incidentLog.belongsTo(teams, {foreignkey: "incident_assignedTeam"});
    incidentResponseLog.belongsTo(incidentLog, {foreignkey: "incidentId"});
    incidentResponseLog.belongsTo(users, {foreignkey: "incidentResponseLog_user"});
    incidentType.belongsTo(teams, {foreignkey: "incidentType_responsible"});
    incidentUrgency.belongsTo(slaList, {foreignkey: "incidentUrgency_sla"});
    issueType.belongsTo(issueCategory, {foreignkey: "issueCategoryId"});
    licenseKeys.belongsTo(softwareAssets, {foreignkey: "softwareId"});
    licenseKeys.belongsTo(users, {foreignkey: "userId"});
    priorityList.belongsTo(slaList, {foreignkey: "priority_sla_id"});
    software_install_status.belongsTo(installStatusList, {foreignkey: "installStatusId"});
    software_install_status.belongsTo(softwareAssets, {foreignkey: "softwareId"});
    software_install_status.belongsto(users, {foreignkey: "userId"});
    softwareAssets.belongsTo(softwareStatus, {foreignkey: "softwareStatusId"});
    softwareAssets.belongsTo(vendors, {foreignkey: "vendorId"});
    taskList.belongsTo(users, {foreignkey: "task_approver"});
    taskList.belongsTo(users, {foreignkey: "task_owner"});
    taskList.belongsTo(requestStatus, {foreignkey: "requestStatusId"});
    taskList.belongsTo(locations, {foreignkey: "shippingLocationId"});
    tasklist.belongsTo(shippingMethods, {foreignkey: "shippingMethodId"});
    taskList.belongsTo(ticketLog, {foreignkey: "ticketId"});
    teamMembership.belongsTo(teams, {foreignkey: "teamId"});
    teamMembership.belongsTo(users, {foreignkey: "userId"});
    ticketLog.belongsTo(users, {foreignkey: "assigned_user"});
    ticketLog.belongsTo(users, {foreignkey: "created_by"});
    ticketLog.belongsTo(assetList, {foreignkey: "assetId"});
    ticketLog.belongsTo(issueCategory, {foreignkey: "issueCategoryId"});
    ticketLog.belongsTo(issueType, {foreignkey: "issueId"});
    ticketLog.belongsTo(locations, {foreignkey: "locationId"});
    ticketLog.belongsTo(priorityList, {foreignkey: "priorityId"});
    ticketLog.belongsTo(requestStatus, {foreignkey: "requestStatusId"});
    ticketLog.belongsTo(resolvedList, {foreignkey: "resolvedId"});
    ticketLog.belongsTo(softwareAssets, {foreignkey: "softwareId"});
    ticketLog.belongsTo(teams, {foreignkey: "teamId"});
    users.belongsTo(departments, {foreignKey: "departmentId"});
    users.belongsTo(roles, {foreignKey: "roleId"});
    users.belongsTo(statuses, {foreignKey: "statusId"});
    vendors.belongsTo(locations, {foreignkey: "locationId"});
    vendors.belongsTo(paymentTerms, {foreignkey: "paymentTermId"});
    workLog.belongsTo(ticketLog, {foreignkey: "ticketId"});
    workLog.belongsTo(users, {foreignkey: "userId"});
  }
}
